/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controlador.ControladorIHC;

/**
 *
 * @author 2017122760293
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private ControladorIHC controladorIHC;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal(ControladorIHC control) {
        initComponents();
        controladorIHC = control;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnReserva = new javax.swing.JButton();
        btnCadCliente = new javax.swing.JButton();
        btnCadLivro = new javax.swing.JButton();
        btnCadAutor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuLivros = new javax.swing.JMenu();
        mnuCadastrarLivro = new javax.swing.JMenuItem();
        mnuPesqLivros = new javax.swing.JMenuItem();
        mnuAutores = new javax.swing.JMenu();
        mnuCadastrarAutor = new javax.swing.JMenuItem();
        mnuPesqAutores = new javax.swing.JMenuItem();
        mnuCliente = new javax.swing.JMenu();
        mnuCadastrarCliente = new javax.swing.JMenuItem();
        mnuPesqClientes = new javax.swing.JMenuItem();
        mnuReservas = new javax.swing.JMenu();
        mnuCadReserva = new javax.swing.JMenuItem();
        mnuPesqReserva = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/3700471-book-books-education-library-literature-reading-study_108741.png"))); // NOI18N
        jLabel2.setText("BIBLIOTECH");

        jPanel2.setBackground(new java.awt.Color(108, 122, 137));

        btnReserva.setBackground(new java.awt.Color(228, 120, 51));
        btnReserva.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnReserva.setText("FAZER RESERVA");
        btnReserva.setBorder(null);
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });

        btnCadCliente.setBackground(new java.awt.Color(228, 120, 51));
        btnCadCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadCliente.setText("CADASTRAR CLIENTE");
        btnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClienteActionPerformed(evt);
            }
        });

        btnCadLivro.setBackground(new java.awt.Color(228, 120, 51));
        btnCadLivro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadLivro.setText("CADASTRAR LIVRO");
        btnCadLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadLivroActionPerformed(evt);
            }
        });

        btnCadAutor.setBackground(new java.awt.Color(228, 120, 51));
        btnCadAutor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadAutor.setText("CADASTRAR AUTOR");
        btnCadAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnCadLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnCadAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 51));

        mnuLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/Books_icon-icons.com_76879.png"))); // NOI18N
        mnuLivros.setText("Livro");
        mnuLivros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnuCadastrarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/add-book_icon-icons.com_71795.png"))); // NOI18N
        mnuCadastrarLivro.setText("Cadastrar Livro");
        mnuCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarLivroActionPerformed(evt);
            }
        });
        mnuLivros.add(mnuCadastrarLivro);

        mnuPesqLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/search_book_open_search_locate_6178.png"))); // NOI18N
        mnuPesqLivros.setText("Consultar Livros");
        mnuPesqLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesqLivrosActionPerformed(evt);
            }
        });
        mnuLivros.add(mnuPesqLivros);

        jMenuBar1.add(mnuLivros);

        mnuAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/writer_person_people_man_you_1633.png"))); // NOI18N
        mnuAutores.setText("Autor");
        mnuAutores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnuCadastrarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/user_add_12818.png"))); // NOI18N
        mnuCadastrarAutor.setText("Cadastrar Autor");
        mnuCadastrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarAutorActionPerformed(evt);
            }
        });
        mnuAutores.add(mnuCadastrarAutor);

        mnuPesqAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/searching-a-person.png"))); // NOI18N
        mnuPesqAutores.setText("Consultar Autores");
        mnuPesqAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesqAutoresActionPerformed(evt);
            }
        });
        mnuAutores.add(mnuPesqAutores);

        jMenuBar1.add(mnuAutores);

        mnuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icons8-gestão-de-cliente-32.png"))); // NOI18N
        mnuCliente.setText("Cliente");
        mnuCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnuCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/user_add_12818.png"))); // NOI18N
        mnuCadastrarCliente.setText("Cadastrar Cliente");
        mnuCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(mnuCadastrarCliente);

        mnuPesqClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/job.png"))); // NOI18N
        mnuPesqClientes.setText("Consultar Clientes");
        mnuPesqClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesqClientesActionPerformed(evt);
            }
        });
        mnuCliente.add(mnuPesqClientes);

        jMenuBar1.add(mnuCliente);

        mnuReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/booking.png"))); // NOI18N
        mnuReservas.setText("Reservas");
        mnuReservas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnuCadReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/calendario.png"))); // NOI18N
        mnuCadReserva.setText("Cadastrar Reserva");
        mnuCadReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadReservaActionPerformed(evt);
            }
        });
        mnuReservas.add(mnuCadReserva);

        mnuPesqReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/bookinggggggggggg.png"))); // NOI18N
        mnuPesqReserva.setText("Consultar Reservas");
        mnuPesqReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesqReservaActionPerformed(evt);
            }
        });
        mnuReservas.add(mnuPesqReserva);

        jMenuBar1.add(mnuReservas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarLivroActionPerformed
    controladorIHC.janelaCadastrarLivros();
    }//GEN-LAST:event_mnuCadastrarLivroActionPerformed

    private void mnuCadastrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarAutorActionPerformed
        controladorIHC.janelaCadastrarAutor();
    }//GEN-LAST:event_mnuCadastrarAutorActionPerformed

    private void mnuCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarClienteActionPerformed
        controladorIHC.janelaCadastrarCliente();
    }//GEN-LAST:event_mnuCadastrarClienteActionPerformed

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        controladorIHC.janelaReserva();
    }//GEN-LAST:event_btnReservaActionPerformed

    private void btnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClienteActionPerformed
        controladorIHC.janelaCadastrarCliente();
    }//GEN-LAST:event_btnCadClienteActionPerformed

    private void btnCadLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadLivroActionPerformed
        controladorIHC.janelaCadastrarLivros();
    }//GEN-LAST:event_btnCadLivroActionPerformed

    private void btnCadAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAutorActionPerformed
        controladorIHC.janelaCadastrarAutor();
    }//GEN-LAST:event_btnCadAutorActionPerformed

    private void mnuPesqLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesqLivrosActionPerformed
        controladorIHC.janelaPesqLivros();
    }//GEN-LAST:event_mnuPesqLivrosActionPerformed

    private void mnuPesqAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesqAutoresActionPerformed
        controladorIHC.janelaPesqAutor();
    }//GEN-LAST:event_mnuPesqAutoresActionPerformed

    private void mnuPesqClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesqClientesActionPerformed
        controladorIHC.janelaPesqCliente();
    }//GEN-LAST:event_mnuPesqClientesActionPerformed

    private void mnuCadReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadReservaActionPerformed
        controladorIHC.janelaReserva();
    }//GEN-LAST:event_mnuCadReservaActionPerformed

    private void mnuPesqReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesqReservaActionPerformed
        controladorIHC.janelaPesqReserva();
    }//GEN-LAST:event_mnuPesqReservaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAutor;
    private javax.swing.JButton btnCadCliente;
    private javax.swing.JButton btnCadLivro;
    private javax.swing.JButton btnReserva;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu mnuAutores;
    private javax.swing.JMenuItem mnuCadReserva;
    private javax.swing.JMenuItem mnuCadastrarAutor;
    private javax.swing.JMenuItem mnuCadastrarCliente;
    private javax.swing.JMenuItem mnuCadastrarLivro;
    private javax.swing.JMenu mnuCliente;
    private javax.swing.JMenu mnuLivros;
    private javax.swing.JMenuItem mnuPesqAutores;
    private javax.swing.JMenuItem mnuPesqClientes;
    private javax.swing.JMenuItem mnuPesqLivros;
    private javax.swing.JMenuItem mnuPesqReserva;
    private javax.swing.JMenu mnuReservas;
    // End of variables declaration//GEN-END:variables
}
